server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
user:
  userServiceUrl: http://localhost:8000/
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@