server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GavinChangCN/spring-cloud-config-repo
          username: gavinchangcn
          password: Gavin666