drop table `user` if exists;
CREATE TABLE `user` (
  id bigint generated by default as identity COMMENT '用户 id',
  username VARCHAR ( 40 ) COMMENT '用户 账号',
  `password` VARCHAR ( 40 ) COMMENT '用户 密码',
  `name` VARCHAR ( 20 ) COMMENT '用户 姓名',
  age INT ( 3 ) COMMENT '用户 年龄',
  balance DECIMAL ( 10, 2 ) COMMENT '用户 余额',
  PRIMARY KEY ( id )
);